#!/usr/bin/env php
<?php
use SimpleLspServer\Application;


require_once __DIR__ . '/vendor/autoload.php';

ini_set('display_errors', 'stderr');

$application  = new Application();

try {
    $application->run();
} catch (Exception $e) {
  echo "fattal errro";
    //$application->renderException($e, $output);
    exit(255);
}




